dataset:
  type: custom
  loader: evoloss.data_loaders:load_cifar10_gray28
  samples: 4000
data_dir: ./data
batch_size: 64
epochs: 1
learning_rate: 0.01
device: cpu
max_train_batches: 100
max_val_batches: 50

# Evolution parameters (quick run)
population_size: 6
tournament_size: 3
max_tree_depth: 4
mutation_rate: 0.3
crossover_rate: 0.7
seed: 42
save_dir: ./results_cifar10
generations: 1
checkpoint_interval: 1
elitism: 2
parallel_eval: false
similarity_threshold: 0.8
diversity_weight: 0.2

# Multi-objective evaluation parameters
w1: 1.0
w2: 0.01
w3: 0.1
w4: 0.1
grad_threshold: 100.0
# Более строгие лимиты для очень быстрого прогона
population_size: 3
max_train_batches: 20
max_val_batches: 10