experiment_name: synth_medium
save_dir: results/run_synth_med
device: cpu
seed: random

dataset:
  type: synthetic
  samples: 4096
  input_dim: 10
  batch_size: 64

model:
  type: linear
  hidden_dim: 32

evolution:
  population_size: 20
  generations: 16
  max_depth: 5
  crossover_rate: 0.7
  mutation_rate: 0.3
  elitism: 2
  target_penalty: 0.8
  seeds_each_gen:
    enabled: true
    avg_accuracy_floor: 0.12
    count: 2

training:
  epochs: 5
  lr: 0.001
  optimizer: Adam
  weight_decay: 0.0001
  
# Evaluation: metric weights
w1: 3.0   # accuracy — most important criterion
w2: 0.01  # complexity penalty — moderate
w3: 0.1   # gradient penalty
w4: 0.02  # convergence speed — small influence
grad_threshold: 30.0