name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # --- 1️⃣ Получаем код ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- 2️⃣ Настройка Python окружения ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- 3️⃣ Кэширование пакетов для ускорения сборок ---
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # --- 4️⃣ Установка зависимостей и пакета ---
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .  # устанавливаем evoloss как локальный пакет
          pip install pytest pytest-cov  # базовые тестовые утилиты

      # --- 5️⃣ Проверка импортов перед тестами ---
      - name: Sanity check imports
        run: python -c "import evoloss; print('✅ Package evoloss imported successfully')"

      # --- 6️⃣ Запуск тестов ---
      - name: Run tests with pytest
        run: |
          PYTHONPATH=. pytest -q --disable-warnings --maxfail=1

      # --- 7️⃣ (опционально) Генерация отчета покрытия ---
      - name: Run tests with coverage report
        if: always()
        run: |
          pytest --cov=evoloss --cov-report=term-missing
